FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y curl

COPY ./model_inference /app/

RUN pip3 install -r requirements.txt

EXPOSE 5000

ENTRYPOINT ["python", "flask_app.py"]